export interface SeriesImage {
  src: string;
  alt: string;
  title?: string;
}

export interface SeriesProject {
  id: string;
  title: string;
  year: string;
  detailLabel?: string;
  description?: string;
  image: string;
  images: SeriesImage[];
  aspectRatio?: string;
}

const createImages = (projectTitle: string, entries: Array<[number, string]>) =>
  entries.map(([number, src]) => ({
    src,
    alt: `${projectTitle} ${String(number).padStart(2, "0")}`,
  }));

export const seriesProjects: SeriesProject[] = [
  {
    id: "futility",
    title: "Futility",
    year: "2025-",
    description:
      "(ongoing project)\n\nRiding a motorbike and simultaneously photographing dogs chasing you is not easy, but it is quite fun. In these moments you feel the fine line between control and chaos, between the will to continue and the need to let go of what is happening. Life, like this chase, is a constant movement — a quest for freedom, shrouded in uncertainty.\n\nFrom a philosophical point of view, this is an encounter with the moment in its purest form — raw, unpredictable, outside the framework of what is planned. To experience the moment means to accept incompleteness and instability as part of the essence of being. To photograph in motion, without a guarantee of a clear frame, is an act of trust in reality as it is.\n\nEscaping the dog is also escaping control — and in those moments, I find a strange kind of freedom. That freedom enters the frame. The photographs I make then are raw and unresolved, but they speak truthfully. Not about appearances, but about how life actually feels when I'm caught inside it.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_01_skrnug.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Futility", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_01_skrnug.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_02_w7qjqt.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_03_wupmnl.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976464/Svilen_Nachev_Futility_04_pz0684.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_05_yxo0xp.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976464/Svilen_Nachev_Futility_06_mo1im5.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976464/Svilen_Nachev_Futility_07_pk8bit.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_08_ex6wk0.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976466/Svilen_Nachev_Futility_09_cop2hl.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_10_pdb2n6.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_11_hlzbrt.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976464/Svilen_Nachev_Futility_12_jwtnwx.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976464/Svilen_Nachev_Futility_13_jcscgw.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_14_gevgbr.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976465/Svilen_Nachev_Futility_15_crbav7.jpg"],
    ]),
  },
  {
    id: "twilight",
    title: "Twilight",
    year: "2024-",
    description:
      "This project uses a single camera, a lens, and a flash to capture light like a thought breaking through darkness. Each frame is created with a single press of the shutter, in a moment where day forgets itself and night has not yet arrived. In this dense silence, time hesitates, and every trace of light remains a fragile reminder, a memory of its own vanishing.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_01_bv4k3f.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Twilight", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_01_bv4k3f.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_02_rr7evg.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_03_lnydzf.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_04_fhtke3.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_05_zfs1gq.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_06_uh9bf6.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_07_cnmqhb.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_08_wft42m.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_09_qfjoqe.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_10_ppytft.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_11_j24ogg.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_12_cs3sot.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976468/Svilen_Nachev_Twilight_13_uowp0t.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_14_xmfqff.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_15_djsgpc.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_16_mu2fgm.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_Twilight_17_fmwerc.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976466/Svilen_Nachev_Twilight_18_jeq5nk.jpg"],
      [19, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976466/Svilen_Nachev_Twilight_19_jnim76.jpg"],
      [20, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_20_ud5ule.jpg"],
      [21, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_21_iztlyu.jpg"],
      [22, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976467/Svilen_Nachev_Twilight_22_zmceqz.jpg"],
      [23, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976466/Svilen_Nachev_Twilight_23_eankt7.jpg"],
      [24, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976466/Svilen_Nachev_Twilight_24_tirair.jpg"],
    ]),
  },
  {
    id: "dream-of-the-flesh",
    title: "Dream Of The Flesh",
    year: "2023-",
    detailLabel: "(ongoing project)",
    description:
      "I find myself consumed by visions where my deepest desires intertwine with the recesses of my subconscious. These moments are a vivid blend of physical longing and uncharted mental landscapes, where the primal aspects of my nature come to life. It's an intoxicating experience, navigating the tension between raw sensuality and the quest for deeper meaning. These inner explorations reveal the complexity of humanity, a constant dance between the needs of the body and the aspirations of the spirit.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_01_wianag.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Dream Of The Flesh", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_01_wianag.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_02_s8i0yy.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_03_m2avrh.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_04_s9iztb.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_The_Dream_05_b2j7ie.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_06_ptr6lf.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_07_glsj4b.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_The_Dream_08_knepcj.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_The_Dream_09_f1arbz.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_10_ziycjc.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_The_Dream_11_r6ea1m.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_12_xnhlgw.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976473/Svilen_Nachev_The_Dream_13_fdryrp.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_14_e6andx.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_15_ltwgtv.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_16_pl5o4b.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_17_svsrqs.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_18_jv3ozw.jpg"],
      [19, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_19_vmqaml.jpg"],
      [20, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_The_Dream_20_tqug70.jpg"],
      [21, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_21_ddf3ay.jpg"],
      [22, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_22_bfjew3.jpg"],
      [23, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_23_jzgo3c.jpg"],
      [24, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_24_xdvnjn.jpg"],
      [25, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_25_o6lffp.jpg"],
      [26, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_26_sgcpor.jpg"],
      [27, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_27_oetslp.jpg"],
      [28, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_28_gon7oe.jpg"],
      [29, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976472/Svilen_Nachev_The_Dream_29_lyg6gz.jpg"],
      [30, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_30_wglpcp.jpg"],
      [31, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_31_vpouxv.jpg"],
      [32, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_32_tttin2.jpg"],
      [33, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976471/Svilen_Nachev_The_Dream_33_a9vope.jpg"],
      [34, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976469/Svilen_Nachev_The_Dream_34_poodzh.jpg"],
      [35, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_35_udsqib.jpg"],
      [36, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976470/Svilen_Nachev_The_Dream_36_jgx7ty.jpg"],
    ]),
  },
  {
    id: "the-illusion-of-meaning",
    title: "The Illusion of Meaning",
    year: "2022-",
    detailLabel: "(ongoing project)",
    description:
      "I often ask myself whether the things I do matter.\nAs we live, we inevitably communicate; we become a factor in others’ lives and actions; our light is present in reality, and we, sometimes without wanting to or realizing it, affect the natural course of events. The controversial nature of photography frequently drags us into the whirlpool of the incomprehensible, further confusing our perception of meaning; the dynamic process itself of seeking meaning can become a goal, which explores the rational and irrational, material and spiritual, reality and illusion.\nAs paradoxical as it may sound, this initial uncertainty can return us to the basics of what makes us human beings.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_01_ohmrhi.jpg",
    aspectRatio: "aspect-video",
    images: createImages("The Illusion of Meaning", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_01_ohmrhi.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Illusion_02_qmmwpc.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Illusion_03_v3ryjt.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_04_jpkae3.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_05_cktpa8.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_06_muntcf.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_07_pumgmg.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Illusion_08_sobswj.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Illusion_09_kockqy.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_10_xlaxfr.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_11_eryfhn.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_12_e4skl9.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_13_i7sma7.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976475/Svilen_Nachev_Illusion_14_p49t9k.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976474/Svilen_Nachev_Illusion_15_agepbu.jpg"],
    ]),
  },
  {
    id: "interiors-from-abandoned-places",
    title: "Interiors From Abandoned Places",
    year: "2021-",
    detailLabel: "(ongoing project)",
    description:
      "Venturing into the neglected recesses of one's mind is akin to traversing the desolate corridors of forgotten structures. In these dimly lit spaces, where echoes of past vibrancy now mingle with shadows, one finds a reflection of the human condition, memories and aspirations left to decay. This visual journey through mental ruins unveils the silent testament to our unexamined lives, urging a contemplative rediscovery. Herein lies the profound truth: amidst the desolation, we uncover the enduring essence of our being, waiting patiently to be reclaimed and understood.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_01_uys2ul.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Interiors From Abandoned Places", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_01_uys2ul.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_02_mgynqg.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_03_xibxk4.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_04_uzakrm.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_05_tzxeum.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_06_jwdbov.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_07_ix6ail.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_08_lldswf.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976478/Svilen_Nachev_Interiors_09_qnxug7.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_10_mavqbo.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_11_kj3tkn.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_12_x7y36l.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_13_tg3vh9.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_14_mlvdzm.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_15_kawggg.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_16_glmkyu.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976480/Svilen_Nachev_Interiors_17_p7kxi2.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_18_uss1mm.jpg"],
      [19, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_19_i8zbj4.jpg"],
      [20, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_20_h6vnza.jpg"],
      [21, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976478/Svilen_Nachev_Interiors_21_p8xq33.jpg"],
      [22, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_22_atpjdw.jpg"],
      [23, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976478/Svilen_Nachev_Interiors_23_eullil.jpg"],
      [24, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_24_hyj2fv.jpg"],
      [25, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_25_urfzoz.jpg"],
      [26, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_26_vxw6jm.jpg"],
      [27, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_27_kixu0w.jpg"],
      [28, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_28_juxqpw.jpg"],
      [29, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976481/Svilen_Nachev_Interiors_29_e45v3n.jpg"],
      [30, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_30_yuhpfc.jpg"],
      [31, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976476/Svilen_Nachev_Interiors_31_lmppfd.jpg"],
      [32, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_32_bgoh04.jpg"],
      [33, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_33_bcl6gr.jpg"],
      [34, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_34_dcd4bj.jpg"],
      [35, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976478/Svilen_Nachev_Interiors_35_hayd6o.jpg"],
      [36, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976477/Svilen_Nachev_Interiors_36_rmhnht.jpg"],
      [37, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976478/Svilen_Nachev_Interiors_37_vonm4l.jpg"],
      [38, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_38_vtauox.jpg"],
      [39, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_39_pt9t9i.jpg"],
      [40, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_40_pxlhqt.jpg"],
      [41, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_41_zezhu4.jpg"],
      [42, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976479/Svilen_Nachev_Interiors_42_kxpr1d.jpg"],
    ]),
  },
  {
    id: "it-aint-gone-till-its-gone",
    title: "It ain't gone 'till it's gone",
    year: "2019-",
    detailLabel: "(ongoing project)",
    description:
      "This work, depicting the repurposing of the mundane tyre, is a portraiture of skepticism towards the disposability of objects - an attitude deeply embedded in communities whichhave encountered prolonged periods of scarcity. The dance between the robust nature of the humble tyre, the ingenuity of humans and the pursuit of longevity has produced a means of architectural landscaping, play, andpolitical statement. The series is a tribute to the somewhat endearing long-lasting presence of these often comedic and slightly absurd objects in our urban landscapes.\n\nText by Irina Gyurcheva",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_01_kkcip3.jpg",
    aspectRatio: "aspect-video",
    images: createImages("It ain't gone 'till it's gone", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_01_kkcip3.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_02_byhwa6.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_03_csvmuo.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976483/Svilen_Nachev_It_aint_gone_till_its_gone_04_edlgmn.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976483/Svilen_Nachev_It_aint_gone_till_its_gone_05_wqhlzw.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_06_hprnlx.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_07_ghkbm6.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_08_fb9ab3.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_09_hbfh7g.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976483/Svilen_Nachev_It_aint_gone_till_its_gone_10_m8sunq.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_11_olvuam.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_12_ogbi5s.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976484/Svilen_Nachev_It_aint_gone_till_its_gone_13_eiotet.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_14_qgfddg.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_15_wnds7r.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_16_n4mix9.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_It_aint_gone_till_its_gone_17_ohpcfa.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_18_ffzer9.jpg"],
      [19, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_19_mjljz5.jpg"],
      [20, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_20_c0kp3v.jpg"],
      [21, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976483/Svilen_Nachev_It_aint_gone_till_its_gone_21_psnnds.jpg"],
      [22, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_22_ar7n6h.jpg"],
      [23, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_23_rmfg3y.jpg"],
      [24, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976482/Svilen_Nachev_It_aint_gone_till_its_gone_24_by5ygk.jpg"],
    ]),
  },
  {
    id: "home",
    title: "Home",
    year: "2019-",
    detailLabel: "(ongoing project)",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_01_w0bitd.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Home", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_01_w0bitd.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_02_x9p2oq.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_03_b2jp0b.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976486/Svilen_Nachev_HOME_04_e4sqbd.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976486/Svilen_Nachev_HOME_05_yd6pee.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_HOME_06_mpfl9e.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_HOME_07_kstsg8.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_08_ze6ioh.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_09_cdugxx.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976486/Svilen_Nachev_HOME_10_ikzgcr.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976486/Svilen_Nachev_HOME_11_dmopdv.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_HOME_12_a0elkx.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976485/Svilen_Nachev_HOME_13_fya9r5.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976486/Svilen_Nachev_HOME_14_n7ccah.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_15_vrzsic.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_16_qp5iol.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_17_cureed.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_18_foa7m0.jpg"],
      [19, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_19_btelqf.jpg"],
      [20, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_20_suqjls.jpg"],
      [21, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_21_wo5yvk.jpg"],
      [22, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_22_yoqjzk.jpg"],
      [23, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976488/Svilen_Nachev_HOME_23_wterhm.jpg"],
      [24, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976487/Svilen_Nachev_HOME_24_e9yfow.jpg"],
    ]),
  },
  {
    id: "animal-planet",
    title: "Animal Planet",
    year: "2016-",
    detailLabel: "(ongoing project)",
    description:
      "Understanding what means to be human is impossible without looking at our relationship with animals. From ancient drawings in caves and the symbolism of zodiac signs to agriculture tozoos and pets, animals have been part of human imagination. This reflection on our ability to connect with sentient life and derive a symbolic meaning from it distinguishes us as species. The instant, non-verbal communication of the animal gaze has a somewhat spiritual quality, albeit often with unequal balance of power, acting as a mirror to prompt a deeper understanding of ourselves and what we value.\n\nText by Irina Gyurcheva",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327975/Svilen_Nachev_Animal_01_xdclly.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Animal Planet", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327975/Svilen_Nachev_Animal_01_xdclly.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327983/Svilen_Nachev_Animal_02_cyllmv.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327984/Svilen_Nachev_Animal_03_vzdemu.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327967/Svilen_Nachev_Animal_04_lmut03.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327978/Svilen_Nachev_Animal_05_qreczl.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327960/Svilen_Nachev_Animal_06_bwgrhh.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327964/Svilen_Nachev_Animal_07_lt9016.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327971/Svilen_Nachev_Animal_08_ujer3z.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327969/Svilen_Nachev_Animal_09_rq4ri7.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327976/Svilen_Nachev_Animal_10_waplur.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327988/Svilen_Nachev_Animal_11_icpent.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327973/Svilen_Nachev_Animal_12_sxtd2t.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327963/Svilen_Nachev_Animal_13_uvafzo.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327968/Svilen_Nachev_Animal_14_jwlfss.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1773327980/Svilen_Nachev_Animal_15_kbv78f.jpg"],
    ]),
  },
  {
    id: "in-between",
    title: "In Between",
    year: "2020-",
    description:
      "This project is about documenting places and people inhabiting the in-between realities of social constructs. It looks at a society within the boundaries of Europe, but not necessarily representative of European way of life. Freedom of political choice is a right, but is repeatedly stifled by corruption and lack of prospects. Its people live between the remnants of the communist ideology and the diminishing hopes for a democratic present. They co-exist (and co-create a future) amidst avariety of ethnic cultures and perceive life through different languages, (both inherited from the past). Technology is often found in its most contrasting, caricature-like extremes.\n\nIt sees childhood, parenting, camaraderie, dilemmas, death ... the uniting power of the human condition.\n\nText by Irina Gyurcheva",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_01_ykbeiu.jpg",
    aspectRatio: "aspect-video",
    images: createImages("In Between", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_01_ykbeiu.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_02_jll2jw.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_03_nffshf.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_04_rlr4h6.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_05_pc6gx8.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976492/Svilen_Nachev_In_Between_06_ezhymr.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976492/Svilen_Nachev_In_Between_07_kz5sc3.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_08_h2yew4.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_09_n6ct7j.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_10_izseod.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_11_pfme6u.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_12_hndoi7.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_In_Between_13_aqdrul.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_14_akxvcj.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_15_pmrqfg.jpg"],
      [16, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976491/Svilen_Nachev_In_Between_16_dhdaor.jpg"],
      [17, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_17_e5c8te.jpg"],
      [18, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976490/Svilen_Nachev_In_Between_18_dz8kt4.jpg"],
    ]),
  },
  {
    id: "to-build-a-house",
    title: "To Build a House",
    year: "2018-",
    description:
      "Children see and experience life in a state of novelty andopenness. Their eyes are always fresh, their minds and hearts thrive on connecting with others. To help their talents and personalities flourish, children need loving relationships with significant adults in a supportive environment. When difficult circumstances such as poverty and broken families affect physical and emotional security, there is a knock-on effect on allparts of a child’s development. This project celebrates second chances for children to be just that – children. It was shot at the School for Arts and Crafts \"Dimitar Ekimov\" Rusalya, Bulgaria - funded entirely by donations - whose dedicated team educates artistically gifted children from poverty-stricken families. The school is aiming to provide equal opportunities, individual approach to learning, professional psychological support and, more importantly, anurturing environment.\n\nText by Irina Gyurcheva",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_01_qrad8x.jpg",
    aspectRatio: "aspect-video",
    images: createImages("To Build a House", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_01_qrad8x.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_02_zg0rm5.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_03_q228gk.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_To_Build_A_House_04_or4vje.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_To_Build_A_House_05_ku31qz.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_06_w2exsw.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_07_uytdqa.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_08_hnk3ra.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976493/Svilen_Nachev_To_Build_A_House_09_nqrrpl.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_To_Build_A_House_10_ii7i0g.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_To_Build_A_House_11_pr6ppv.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_To_Build_A_House_12_ccxvu9.jpg"],
    ]),
  },
  {
    id: "persin",
    title: "Persin",
    year: "2017",
    description:
      "\"Those who can not remember the past are condemned to repeat it.\" - George Santayana\n\nBelene concentration camp was part of the network offorced labour camps in Communist Bulgaria. It was located on the Persin (Belene) Island, between two branches of the Danube river.\n\nThe opponents of the communist dictatorship were forced to live in inhuman conditions ñ daily physical labour, intolerable demands and under constant armed guard. They were forced to live in bunkers and huts which theybuilt themselves with whatever materials they could find. Hunger was the most terrible thing they were subject to.\n\nTens of thousands of prisoners passed through the camps.\n\nEvery year from 1990 at the end of May or the beginning of June, an annual pilgrimage to the site of the former camp is held. For the rest of the year the island is closed for visitors. This pictures are from 2017 annual service of remembrance for the victims of the communist camps.",
    image: "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_01_vuidvu.jpg",
    aspectRatio: "aspect-video",
    images: createImages("Persin", [
      [1, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_01_vuidvu.jpg"],
      [2, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_02_gkfnqd.jpg"],
      [3, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_03_x4xuzj.jpg"],
      [4, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_04_hl13zf.jpg"],
      [5, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_05_qsskjk.jpg"],
      [6, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_Persin_06_xhzz3f.jpg"],
      [7, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_07_fff6fa.jpg"],
      [8, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_08_pzlmlq.jpg"],
      [9, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_09_eac0i5.jpg"],
      [10, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_10_ivqdxy.jpg"],
      [11, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_11_s7xg7v.jpg"],
      [12, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976494/Svilen_Nachev_Persin_12_fl5enh.jpg"],
      [13, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976495/Svilen_Nachev_Persin_13_sg3cfc.jpg"],
      [14, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976496/Svilen_Nachev_Persin_14_efosns.jpg"],
      [15, "https://res.cloudinary.com/dbkvqqpan/image/upload/v1772976497/Svilen_Nachev_Persin_15_frmxav.jpg"],
    ]),
  },
];

export const seriesProjectMap = Object.fromEntries(
  seriesProjects.map((project) => [project.id, project]),
) as Record<string, SeriesProject>;
